### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Genera la composizione di due funzioni.


  Ovvero, date due funzioni $f $ e $g $, restituisce una nuova funzione che rappresenta $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Seconda funzione da applicare.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Prima funzione da applicare.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Una nuova funzione $h $ tale che per tutti gli input $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Tipo di input della prima funzione da applicare.
- uid: "'U"
  summary: Il tipo di output della prima funzione da applicare e il tipo di input della seconda funzione da applicare.
- uid: "'V"
  summary: Tipo di output della seconda funzione da applicare.
ms.openlocfilehash: 69fbd6a4fafbc61a63e41257b7100303fd48d4d4
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 10/31/2019
ms.locfileid: "73223072"
