### YamlMime:QSharpType
uid: microsoft.quantum.canon.decomposedintotimestepsca
name: DecomposedIntoTimeStepsCA
type: function
namespace: Microsoft.Quantum.Canon
summary: Restituisce un'operazione che implementa l'integratore Trotter – Suzuki per una determinata operazione.
remarks: >-
  Quando viene chiamato `order` con uguale `1`a, questa funzione restituisce un'operazione che può essere simulata da Trotter di ordine più basso-Suzuki integrator $ $ \begin{align} S_1 (\lambda) = \ prod_ {j = 1} ^ {m} e ^ {H_j \lambda}, \end{align} $ $ dove è stata seguita la notazione [di quante-pH/0508139](https://arxiv.org/abs/quant-ph/0508139) e si lascia che $ \lambda $ sia il tempo di evoluzione (rappresentato dal primo input dell'operazione restituita),\{e\}consentono a $ H_j _ {j = 1} ^ {m} $ di essere il set di generatori dinamici (asimmetria-Hermitiane) `op(j, lambda, _)` integrati, in modo che venga simulato dall'operatore unitario $e ^ {H_j \lambda} $.


  Analogamente, `order` un `2` oggetto di restituisce il secondo ordine simmetrico Trotter – Suzuki integrator $ $ \begin{align} S_2 (\lambda) = \ prod_ {j = 1} ^ {m} e ^ {H_k \lambda/2} \ prod_ {j ' = m{1} } ^ e ^ {H_ {j '} \lambda/2}.

  \end{align} $ $


  I valori pari più `order` elevati di vengono implementati usando la costruzione ricorsiva di [quanti-pH/0508139](https://arxiv.org/abs/quant-ph/0508139).
syntax: "function DecomposedIntoTimeStepsCA ((nSteps : Int, op : ((Int, Double, 'T) => Unit is Adj + Ctl)), trotterOrder : Int) : ((Double, 'T) => Unit is Adj + Ctl)"
references: '- [*D. W. Berry, G. Ahokas, R. Cleve, B. C. Sanders*](https://arxiv.org/abs/quant-ph/0508139)'
input:
  content: "((nSteps : Int, op : ((Int, Double, 'T) => Unit is Adj + Ctl)), trotterOrder : Int)"
  types:
  - name: nSteps
    summary: Numero di operazioni da scomporre in passaggi temporali.
    isPrimitive: true
    uid: Int
  - name: op
    summary: Operazione che accetta un input di indice (tipo `Int`) e un input temporale (tipo `Double`) per la scomposizione.
    isOperation: true
    input:
      types:
      - isPrimitive: true
        uid: Int
      - isPrimitive: true
        uid: Double
      - uid: "'T"
        isLocal: true
    output:
      types:
      - isPrimitive: true
        uid: Unit
    functors:
    - Adjoint
    - Controlled
  - name: trotterOrder
    summary: >-
      Seleziona l'ordine di utilizzo di Trotter-Suzuki Integrator.

      Ordine 1 e anche Orders 2, 4, 6,... sono attualmente supportati.
    isPrimitive: true
    uid: Int
output:
  content: ((Double, 'T) => Unit is Adj + Ctl)
  types:
  - summary: Restituisce un Unity che implementa l'integratore Trotter – Suzuki, dove il `Double` primo parametro è la dimensione del passaggio di integrazione e il secondo parametro è la destinazione su cui si è agito.
    isOperation: true
    input:
      types:
      - isPrimitive: true
        uid: Double
      - uid: "'T"
        isLocal: true
    output:
      types:
      - isPrimitive: true
        uid: Unit
    functors:
    - Adjoint
    - Controlled
typeParameters:
- uid: "'T"
  summary: Tipo su cui ogni passaggio temporale deve agire; in genere, `Qubit[]` o `Qubit`.
metadata:
  ms.openlocfilehash: 1fdb15e9a28c24ac58f026a89779951b982edb27
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82680245"
