### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Restituisce la composizione di due funzioni.


  Date due funzioni $f $ e $g $, restituisce una nuova funzione che rappresenta $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Seconda funzione da applicare.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Prima funzione da applicare.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Una nuova funzione $h $ tale che per tutti gli input $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Tipo di input della prima funzione da applicare.
- uid: "'U"
  summary: Il tipo di output della prima funzione da applicare e il tipo di input della seconda funzione da applicare.
- uid: "'V"
  summary: Tipo di output della seconda funzione da applicare.
metadata:
  ms.openlocfilehash: 77037411aace0f69850b62322f3e63d6a34358ed
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82675808"
